import { ReactElement } from 'react';
import { DashboardLayout } from '@ui/layout/DashboardLayout';
import { Banner } from '@ui/module/home/Banner';
import Head from 'next/head';

import { NextPageWithLayout } from '../_app';

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="pb-10">
        <div className="py-10 md:my-20">
          <Banner />
        </div>
      </main>
    </>
  );
};

Home.getLayout = (page: ReactElement) => (
  <DashboardLayout>{page}</DashboardLayout>
);

export default Home;
