import { ReactElement } from 'react';
import { HomeLayout } from '@ui/layout/HomeLayout';
import { Banner } from '@ui/module/home/Banner';
import { ServiceCard } from '@ui/module/home/ServiceCard';
import Head from 'next/head';

import { NextPageWithLayout } from './_app';

const services = [
  {
    description: ` Lorem ipsum dolor, sit amet consectetur adipisicing elit. Expedita
laboriosam architecto beatae, iure eaque similique accusamus rerum,
ipsam ullam magnam ducimus! Eum vel a vitae, expedita libero doloremque
dicta pariatur?`,
    icon: '/icons/mockup.png',
    title: ' Easily capture and create expensive report.',
  },
  {
    description: ` Lorem ipsum dolor, sit amet consectetur adipisicing elit. Expedita
laboriosam architecto beatae, iure eaque similique accusamus rerum,
ipsam ullam magnam ducimus! Eum vel a vitae, expedita libero doloremque
dicta pariatur?`,
    icon: '/icons/manager.png',
    title: 'Review and manage expensive workflow.',
  },
  {
    description: ` Lorem ipsum dolor, sit amet consectetur adipisicing elit. Expedita
laboriosam architecto beatae, iure eaque similique accusamus rerum,
ipsam ullam magnam ducimus! Eum vel a vitae, expedita libero doloremque
dicta pariatur?`,
    icon: '/icons/calendar.png',
    title: 'Save employee and business owner time.',
  },
];
const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="pb-10">
        <div className="py-10 md:my-20">
          <Banner />
        </div>
        <div className="grid gap-6 md:grid-cols-3">
          {services.map((service, Idx) => (
            <ServiceCard {...service} key={Idx} />
          ))}
        </div>
      </main>
    </>
  );
};

Home.getLayout = (page: ReactElement) => <HomeLayout>{page}</HomeLayout>;

export default Home;
